### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by mar1ged** [rycus86/docker-prometheus-node-exporter#1]
I had to replace `--collector.procfs` and `--collector.sysfs` with `path.procfs` and `path.sysfs`. 

See the docs for slightly more details:

      --path.procfs="/proc"     procfs mountpoint.
      --path.sysfs="/sys"       sysfs mountpoint.

**Comment by rycus86** [comment]
Thanks for bringing this to my attention! I've missed the parameter change between 0.14 and 0.15.
